### ISSUE TITLE
Lack of scripts

### ISSUE THREAD

**Issue by Ericwst** [openmedlab/Endo-FM#2]
Dear author, Thanks for your work. I'm curious about where to find the scripts folder?
# PolypDiag (Classification)
cd Endo-FM
bash scripts/eval_finetune_polypdiag.sh

# CVC (Segmentation)
cd Endo-FM/TransUNet
python train.py

# KUMC (Detection)
cd Endo-FM/STMT
python setup.py build develop
python -m torch.distributed.launch \
    --nproc_per_node=1 \
    tools/train_net.py \
    --master_port=$((RANDOM + 10000)) \
    --config-file configs/STFT/kumc_R_50_STFT.yaml \
    OUTPUT_DIR log_dir/kumc_finetune

**Comment by Kyfafyd** [comment]
These scripts can be find in [Med-AIR Page](https://github.com/med-air/Endo-FM).
